"""Initial migration.

Revision ID: 382af4d42767
Revises: 
Create Date: 2021-03-29 10:02:01.400131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382af4d42767'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('middle', sa.String(), nullable=True),
    sa.Column('surnom', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bban', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('artist', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artist', 'contact', ['contact_id'], ['id'])
    op.create_unique_constraint(None, 'catalog', ['catalog_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalog', type_='unique')
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'contact_id')
    op.drop_table('contact')
    # ### end Alembic commands ###
